// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datamessage.proto

package sfs.proc.msg;

public final class DataMessageProto {
  private DataMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DataMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string srcpath = 1;
    boolean hasSrcpath();
    String getSrcpath();
    
    // repeated .sfs.proc.msg.TimeValSet data = 2;
    java.util.List<sfs.proc.msg.DataMessageProto.TimeValSet> 
        getDataList();
    sfs.proc.msg.DataMessageProto.TimeValSet getData(int index);
    int getDataCount();
    java.util.List<? extends sfs.proc.msg.DataMessageProto.TimeValSetOrBuilder> 
        getDataOrBuilderList();
    sfs.proc.msg.DataMessageProto.TimeValSetOrBuilder getDataOrBuilder(
        int index);
    
    // optional .sfs.proc.msg.PropertyMessage properties = 3;
    boolean hasProperties();
    sfs.proc.msg.DataMessageProto.PropertyMessage getProperties();
    sfs.proc.msg.DataMessageProto.PropertyMessageOrBuilder getPropertiesOrBuilder();
    
    // required .sfs.proc.msg.DataMessage.DataMessageType type = 9;
    boolean hasType();
    sfs.proc.msg.DataMessageProto.DataMessage.DataMessageType getType();
  }
  public static final class DataMessage extends
      com.google.protobuf.GeneratedMessage
      implements DataMessageOrBuilder {
    // Use DataMessage.newBuilder() to construct.
    private DataMessage(Builder builder) {
      super(builder);
    }
    private DataMessage(boolean noInit) {}
    
    private static final DataMessage defaultInstance;
    public static DataMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public DataMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sfs.proc.msg.DataMessageProto.internal_static_sfs_proc_msg_DataMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sfs.proc.msg.DataMessageProto.internal_static_sfs_proc_msg_DataMessage_fieldAccessorTable;
    }
    
    public enum DataMessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      DATA_IN(0, 1),
      DATA_OUT(1, 2),
      ;
      
      public static final int DATA_IN_VALUE = 1;
      public static final int DATA_OUT_VALUE = 2;
      
      
      public final int getNumber() { return value; }
      
      public static DataMessageType valueOf(int value) {
        switch (value) {
          case 1: return DATA_IN;
          case 2: return DATA_OUT;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<DataMessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<DataMessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataMessageType>() {
              public DataMessageType findValueByNumber(int number) {
                return DataMessageType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return sfs.proc.msg.DataMessageProto.DataMessage.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final DataMessageType[] VALUES = {
        DATA_IN, DATA_OUT, 
      };
      
      public static DataMessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private DataMessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:sfs.proc.msg.DataMessage.DataMessageType)
    }
    
    private int bitField0_;
    // optional string srcpath = 1;
    public static final int SRCPATH_FIELD_NUMBER = 1;
    private java.lang.Object srcpath_;
    public boolean hasSrcpath() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getSrcpath() {
      java.lang.Object ref = srcpath_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          srcpath_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSrcpathBytes() {
      java.lang.Object ref = srcpath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        srcpath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .sfs.proc.msg.TimeValSet data = 2;
    public static final int DATA_FIELD_NUMBER = 2;
    private java.util.List<sfs.proc.msg.DataMessageProto.TimeValSet> data_;
    public java.util.List<sfs.proc.msg.DataMessageProto.TimeValSet> getDataList() {
      return data_;
    }
    public java.util.List<? extends sfs.proc.msg.DataMessageProto.TimeValSetOrBuilder> 
        getDataOrBuilderList() {
      return data_;
    }
    public int getDataCount() {
      return data_.size();
    }
    public sfs.proc.msg.DataMessageProto.TimeValSet getData(int index) {
      return data_.get(index);
    }
    public sfs.proc.msg.DataMessageProto.TimeValSetOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }
    
    // optional .sfs.proc.msg.PropertyMessage properties = 3;
    public static final int PROPERTIES_FIELD_NUMBER = 3;
    private sfs.proc.msg.DataMessageProto.PropertyMessage properties_;
    public boolean hasProperties() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public sfs.proc.msg.DataMessageProto.PropertyMessage getProperties() {
      return properties_;
    }
    public sfs.proc.msg.DataMessageProto.PropertyMessageOrBuilder getPropertiesOrBuilder() {
      return properties_;
    }
    
    // required .sfs.proc.msg.DataMessage.DataMessageType type = 9;
    public static final int TYPE_FIELD_NUMBER = 9;
    private sfs.proc.msg.DataMessageProto.DataMessage.DataMessageType type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public sfs.proc.msg.DataMessageProto.DataMessage.DataMessageType getType() {
      return type_;
    }
    
    private void initFields() {
      srcpath_ = "";
      data_ = java.util.Collections.emptyList();
      properties_ = sfs.proc.msg.DataMessageProto.PropertyMessage.getDefaultInstance();
      type_ = sfs.proc.msg.DataMessageProto.DataMessage.DataMessageType.DATA_IN;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasProperties()) {
        if (!getProperties().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSrcpathBytes());
      }
      for (int i = 0; i < data_.size(); i++) {
        output.writeMessage(2, data_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(3, properties_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(9, type_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSrcpathBytes());
      }
      for (int i = 0; i < data_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, data_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, properties_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(9, type_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static sfs.proc.msg.DataMessageProto.DataMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sfs.proc.msg.DataMessageProto.DataMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sfs.proc.msg.DataMessageProto.DataMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sfs.proc.msg.DataMessageProto.DataMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sfs.proc.msg.DataMessageProto.DataMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sfs.proc.msg.DataMessageProto.DataMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static sfs.proc.msg.DataMessageProto.DataMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sfs.proc.msg.DataMessageProto.DataMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sfs.proc.msg.DataMessageProto.DataMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sfs.proc.msg.DataMessageProto.DataMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(sfs.proc.msg.DataMessageProto.DataMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements sfs.proc.msg.DataMessageProto.DataMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sfs.proc.msg.DataMessageProto.internal_static_sfs_proc_msg_DataMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sfs.proc.msg.DataMessageProto.internal_static_sfs_proc_msg_DataMessage_fieldAccessorTable;
      }
      
      // Construct using sfs.proc.msg.DataMessageProto.DataMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDataFieldBuilder();
          getPropertiesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        srcpath_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          dataBuilder_.clear();
        }
        if (propertiesBuilder_ == null) {
          properties_ = sfs.proc.msg.DataMessageProto.PropertyMessage.getDefaultInstance();
        } else {
          propertiesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = sfs.proc.msg.DataMessageProto.DataMessage.DataMessageType.DATA_IN;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sfs.proc.msg.DataMessageProto.DataMessage.getDescriptor();
      }
      
      public sfs.proc.msg.DataMessageProto.DataMessage getDefaultInstanceForType() {
        return sfs.proc.msg.DataMessageProto.DataMessage.getDefaultInstance();
      }
      
      public sfs.proc.msg.DataMessageProto.DataMessage build() {
        sfs.proc.msg.DataMessageProto.DataMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private sfs.proc.msg.DataMessageProto.DataMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        sfs.proc.msg.DataMessageProto.DataMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public sfs.proc.msg.DataMessageProto.DataMessage buildPartial() {
        sfs.proc.msg.DataMessageProto.DataMessage result = new sfs.proc.msg.DataMessageProto.DataMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.srcpath_ = srcpath_;
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            data_ = java.util.Collections.unmodifiableList(data_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        if (propertiesBuilder_ == null) {
          result.properties_ = properties_;
        } else {
          result.properties_ = propertiesBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sfs.proc.msg.DataMessageProto.DataMessage) {
          return mergeFrom((sfs.proc.msg.DataMessageProto.DataMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(sfs.proc.msg.DataMessageProto.DataMessage other) {
        if (other == sfs.proc.msg.DataMessageProto.DataMessage.getDefaultInstance()) return this;
        if (other.hasSrcpath()) {
          setSrcpath(other.getSrcpath());
        }
        if (dataBuilder_ == null) {
          if (!other.data_.isEmpty()) {
            if (data_.isEmpty()) {
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureDataIsMutable();
              data_.addAll(other.data_);
            }
            onChanged();
          }
        } else {
          if (!other.data_.isEmpty()) {
            if (dataBuilder_.isEmpty()) {
              dataBuilder_.dispose();
              dataBuilder_ = null;
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000002);
              dataBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDataFieldBuilder() : null;
            } else {
              dataBuilder_.addAllMessages(other.data_);
            }
          }
        }
        if (other.hasProperties()) {
          mergeProperties(other.getProperties());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (hasProperties()) {
          if (!getProperties().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              srcpath_ = input.readBytes();
              break;
            }
            case 18: {
              sfs.proc.msg.DataMessageProto.TimeValSet.Builder subBuilder = sfs.proc.msg.DataMessageProto.TimeValSet.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addData(subBuilder.buildPartial());
              break;
            }
            case 26: {
              sfs.proc.msg.DataMessageProto.PropertyMessage.Builder subBuilder = sfs.proc.msg.DataMessageProto.PropertyMessage.newBuilder();
              if (hasProperties()) {
                subBuilder.mergeFrom(getProperties());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setProperties(subBuilder.buildPartial());
              break;
            }
            case 72: {
              int rawValue = input.readEnum();
              sfs.proc.msg.DataMessageProto.DataMessage.DataMessageType value = sfs.proc.msg.DataMessageProto.DataMessage.DataMessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(9, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                type_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string srcpath = 1;
      private java.lang.Object srcpath_ = "";
      public boolean hasSrcpath() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getSrcpath() {
        java.lang.Object ref = srcpath_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          srcpath_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSrcpath(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        srcpath_ = value;
        onChanged();
        return this;
      }
      public Builder clearSrcpath() {
        bitField0_ = (bitField0_ & ~0x00000001);
        srcpath_ = getDefaultInstance().getSrcpath();
        onChanged();
        return this;
      }
      void setSrcpath(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        srcpath_ = value;
        onChanged();
      }
      
      // repeated .sfs.proc.msg.TimeValSet data = 2;
      private java.util.List<sfs.proc.msg.DataMessageProto.TimeValSet> data_ =
        java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          data_ = new java.util.ArrayList<sfs.proc.msg.DataMessageProto.TimeValSet>(data_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          sfs.proc.msg.DataMessageProto.TimeValSet, sfs.proc.msg.DataMessageProto.TimeValSet.Builder, sfs.proc.msg.DataMessageProto.TimeValSetOrBuilder> dataBuilder_;
      
      public java.util.List<sfs.proc.msg.DataMessageProto.TimeValSet> getDataList() {
        if (dataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(data_);
        } else {
          return dataBuilder_.getMessageList();
        }
      }
      public int getDataCount() {
        if (dataBuilder_ == null) {
          return data_.size();
        } else {
          return dataBuilder_.getCount();
        }
      }
      public sfs.proc.msg.DataMessageProto.TimeValSet getData(int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);
        } else {
          return dataBuilder_.getMessage(index);
        }
      }
      public Builder setData(
          int index, sfs.proc.msg.DataMessageProto.TimeValSet value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.set(index, value);
          onChanged();
        } else {
          dataBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setData(
          int index, sfs.proc.msg.DataMessageProto.TimeValSet.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addData(sfs.proc.msg.DataMessageProto.TimeValSet value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(value);
          onChanged();
        } else {
          dataBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addData(
          int index, sfs.proc.msg.DataMessageProto.TimeValSet value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(index, value);
          onChanged();
        } else {
          dataBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addData(
          sfs.proc.msg.DataMessageProto.TimeValSet.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addData(
          int index, sfs.proc.msg.DataMessageProto.TimeValSet.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllData(
          java.lang.Iterable<? extends sfs.proc.msg.DataMessageProto.TimeValSet> values) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          super.addAll(values, data_);
          onChanged();
        } else {
          dataBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        return this;
      }
      public Builder removeData(int index) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.remove(index);
          onChanged();
        } else {
          dataBuilder_.remove(index);
        }
        return this;
      }
      public sfs.proc.msg.DataMessageProto.TimeValSet.Builder getDataBuilder(
          int index) {
        return getDataFieldBuilder().getBuilder(index);
      }
      public sfs.proc.msg.DataMessageProto.TimeValSetOrBuilder getDataOrBuilder(
          int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);  } else {
          return dataBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends sfs.proc.msg.DataMessageProto.TimeValSetOrBuilder> 
           getDataOrBuilderList() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(data_);
        }
      }
      public sfs.proc.msg.DataMessageProto.TimeValSet.Builder addDataBuilder() {
        return getDataFieldBuilder().addBuilder(
            sfs.proc.msg.DataMessageProto.TimeValSet.getDefaultInstance());
      }
      public sfs.proc.msg.DataMessageProto.TimeValSet.Builder addDataBuilder(
          int index) {
        return getDataFieldBuilder().addBuilder(
            index, sfs.proc.msg.DataMessageProto.TimeValSet.getDefaultInstance());
      }
      public java.util.List<sfs.proc.msg.DataMessageProto.TimeValSet.Builder> 
           getDataBuilderList() {
        return getDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          sfs.proc.msg.DataMessageProto.TimeValSet, sfs.proc.msg.DataMessageProto.TimeValSet.Builder, sfs.proc.msg.DataMessageProto.TimeValSetOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              sfs.proc.msg.DataMessageProto.TimeValSet, sfs.proc.msg.DataMessageProto.TimeValSet.Builder, sfs.proc.msg.DataMessageProto.TimeValSetOrBuilder>(
                  data_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }
      
      // optional .sfs.proc.msg.PropertyMessage properties = 3;
      private sfs.proc.msg.DataMessageProto.PropertyMessage properties_ = sfs.proc.msg.DataMessageProto.PropertyMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          sfs.proc.msg.DataMessageProto.PropertyMessage, sfs.proc.msg.DataMessageProto.PropertyMessage.Builder, sfs.proc.msg.DataMessageProto.PropertyMessageOrBuilder> propertiesBuilder_;
      public boolean hasProperties() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public sfs.proc.msg.DataMessageProto.PropertyMessage getProperties() {
        if (propertiesBuilder_ == null) {
          return properties_;
        } else {
          return propertiesBuilder_.getMessage();
        }
      }
      public Builder setProperties(sfs.proc.msg.DataMessageProto.PropertyMessage value) {
        if (propertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          properties_ = value;
          onChanged();
        } else {
          propertiesBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setProperties(
          sfs.proc.msg.DataMessageProto.PropertyMessage.Builder builderForValue) {
        if (propertiesBuilder_ == null) {
          properties_ = builderForValue.build();
          onChanged();
        } else {
          propertiesBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeProperties(sfs.proc.msg.DataMessageProto.PropertyMessage value) {
        if (propertiesBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              properties_ != sfs.proc.msg.DataMessageProto.PropertyMessage.getDefaultInstance()) {
            properties_ =
              sfs.proc.msg.DataMessageProto.PropertyMessage.newBuilder(properties_).mergeFrom(value).buildPartial();
          } else {
            properties_ = value;
          }
          onChanged();
        } else {
          propertiesBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearProperties() {
        if (propertiesBuilder_ == null) {
          properties_ = sfs.proc.msg.DataMessageProto.PropertyMessage.getDefaultInstance();
          onChanged();
        } else {
          propertiesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public sfs.proc.msg.DataMessageProto.PropertyMessage.Builder getPropertiesBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getPropertiesFieldBuilder().getBuilder();
      }
      public sfs.proc.msg.DataMessageProto.PropertyMessageOrBuilder getPropertiesOrBuilder() {
        if (propertiesBuilder_ != null) {
          return propertiesBuilder_.getMessageOrBuilder();
        } else {
          return properties_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          sfs.proc.msg.DataMessageProto.PropertyMessage, sfs.proc.msg.DataMessageProto.PropertyMessage.Builder, sfs.proc.msg.DataMessageProto.PropertyMessageOrBuilder> 
          getPropertiesFieldBuilder() {
        if (propertiesBuilder_ == null) {
          propertiesBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              sfs.proc.msg.DataMessageProto.PropertyMessage, sfs.proc.msg.DataMessageProto.PropertyMessage.Builder, sfs.proc.msg.DataMessageProto.PropertyMessageOrBuilder>(
                  properties_,
                  getParentForChildren(),
                  isClean());
          properties_ = null;
        }
        return propertiesBuilder_;
      }
      
      // required .sfs.proc.msg.DataMessage.DataMessageType type = 9;
      private sfs.proc.msg.DataMessageProto.DataMessage.DataMessageType type_ = sfs.proc.msg.DataMessageProto.DataMessage.DataMessageType.DATA_IN;
      public boolean hasType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public sfs.proc.msg.DataMessageProto.DataMessage.DataMessageType getType() {
        return type_;
      }
      public Builder setType(sfs.proc.msg.DataMessageProto.DataMessage.DataMessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = sfs.proc.msg.DataMessageProto.DataMessage.DataMessageType.DATA_IN;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:sfs.proc.msg.DataMessage)
    }
    
    static {
      defaultInstance = new DataMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:sfs.proc.msg.DataMessage)
  }
  
  public interface TimeValSetOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional uint64 ts = 1;
    boolean hasTs();
    long getTs();
    
    // repeated uint64 val = 2 [packed = true];
    java.util.List<java.lang.Long> getValList();
    int getValCount();
    long getVal(int index);
  }
  public static final class TimeValSet extends
      com.google.protobuf.GeneratedMessage
      implements TimeValSetOrBuilder {
    // Use TimeValSet.newBuilder() to construct.
    private TimeValSet(Builder builder) {
      super(builder);
    }
    private TimeValSet(boolean noInit) {}
    
    private static final TimeValSet defaultInstance;
    public static TimeValSet getDefaultInstance() {
      return defaultInstance;
    }
    
    public TimeValSet getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sfs.proc.msg.DataMessageProto.internal_static_sfs_proc_msg_TimeValSet_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sfs.proc.msg.DataMessageProto.internal_static_sfs_proc_msg_TimeValSet_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional uint64 ts = 1;
    public static final int TS_FIELD_NUMBER = 1;
    private long ts_;
    public boolean hasTs() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getTs() {
      return ts_;
    }
    
    // repeated uint64 val = 2 [packed = true];
    public static final int VAL_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Long> val_;
    public java.util.List<java.lang.Long>
        getValList() {
      return val_;
    }
    public int getValCount() {
      return val_.size();
    }
    public long getVal(int index) {
      return val_.get(index);
    }
    private int valMemoizedSerializedSize = -1;
    
    private void initFields() {
      ts_ = 0L;
      val_ = java.util.Collections.emptyList();;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, ts_);
      }
      if (getValList().size() > 0) {
        output.writeRawVarint32(18);
        output.writeRawVarint32(valMemoizedSerializedSize);
      }
      for (int i = 0; i < val_.size(); i++) {
        output.writeUInt64NoTag(val_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, ts_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < val_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt64SizeNoTag(val_.get(i));
        }
        size += dataSize;
        if (!getValList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        valMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static sfs.proc.msg.DataMessageProto.TimeValSet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sfs.proc.msg.DataMessageProto.TimeValSet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sfs.proc.msg.DataMessageProto.TimeValSet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sfs.proc.msg.DataMessageProto.TimeValSet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sfs.proc.msg.DataMessageProto.TimeValSet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sfs.proc.msg.DataMessageProto.TimeValSet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static sfs.proc.msg.DataMessageProto.TimeValSet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sfs.proc.msg.DataMessageProto.TimeValSet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sfs.proc.msg.DataMessageProto.TimeValSet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sfs.proc.msg.DataMessageProto.TimeValSet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(sfs.proc.msg.DataMessageProto.TimeValSet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements sfs.proc.msg.DataMessageProto.TimeValSetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sfs.proc.msg.DataMessageProto.internal_static_sfs_proc_msg_TimeValSet_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sfs.proc.msg.DataMessageProto.internal_static_sfs_proc_msg_TimeValSet_fieldAccessorTable;
      }
      
      // Construct using sfs.proc.msg.DataMessageProto.TimeValSet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        ts_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        val_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sfs.proc.msg.DataMessageProto.TimeValSet.getDescriptor();
      }
      
      public sfs.proc.msg.DataMessageProto.TimeValSet getDefaultInstanceForType() {
        return sfs.proc.msg.DataMessageProto.TimeValSet.getDefaultInstance();
      }
      
      public sfs.proc.msg.DataMessageProto.TimeValSet build() {
        sfs.proc.msg.DataMessageProto.TimeValSet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private sfs.proc.msg.DataMessageProto.TimeValSet buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        sfs.proc.msg.DataMessageProto.TimeValSet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public sfs.proc.msg.DataMessageProto.TimeValSet buildPartial() {
        sfs.proc.msg.DataMessageProto.TimeValSet result = new sfs.proc.msg.DataMessageProto.TimeValSet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ts_ = ts_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          val_ = java.util.Collections.unmodifiableList(val_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.val_ = val_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sfs.proc.msg.DataMessageProto.TimeValSet) {
          return mergeFrom((sfs.proc.msg.DataMessageProto.TimeValSet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(sfs.proc.msg.DataMessageProto.TimeValSet other) {
        if (other == sfs.proc.msg.DataMessageProto.TimeValSet.getDefaultInstance()) return this;
        if (other.hasTs()) {
          setTs(other.getTs());
        }
        if (!other.val_.isEmpty()) {
          if (val_.isEmpty()) {
            val_ = other.val_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureValIsMutable();
            val_.addAll(other.val_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              ts_ = input.readUInt64();
              break;
            }
            case 16: {
              ensureValIsMutable();
              val_.add(input.readUInt64());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addVal(input.readUInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional uint64 ts = 1;
      private long ts_ ;
      public boolean hasTs() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getTs() {
        return ts_;
      }
      public Builder setTs(long value) {
        bitField0_ |= 0x00000001;
        ts_ = value;
        onChanged();
        return this;
      }
      public Builder clearTs() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ts_ = 0L;
        onChanged();
        return this;
      }
      
      // repeated uint64 val = 2 [packed = true];
      private java.util.List<java.lang.Long> val_ = java.util.Collections.emptyList();;
      private void ensureValIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          val_ = new java.util.ArrayList<java.lang.Long>(val_);
          bitField0_ |= 0x00000002;
         }
      }
      public java.util.List<java.lang.Long>
          getValList() {
        return java.util.Collections.unmodifiableList(val_);
      }
      public int getValCount() {
        return val_.size();
      }
      public long getVal(int index) {
        return val_.get(index);
      }
      public Builder setVal(
          int index, long value) {
        ensureValIsMutable();
        val_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addVal(long value) {
        ensureValIsMutable();
        val_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllVal(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureValIsMutable();
        super.addAll(values, val_);
        onChanged();
        return this;
      }
      public Builder clearVal() {
        val_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:sfs.proc.msg.TimeValSet)
    }
    
    static {
      defaultInstance = new TimeValSet(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:sfs.proc.msg.TimeValSet)
  }
  
  public interface PropertyMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string description = 1;
    boolean hasDescription();
    String getDescription();
    
    // repeated .sfs.proc.msg.PropertyMap pmap = 2;
    java.util.List<sfs.proc.msg.DataMessageProto.PropertyMap> 
        getPmapList();
    sfs.proc.msg.DataMessageProto.PropertyMap getPmap(int index);
    int getPmapCount();
    java.util.List<? extends sfs.proc.msg.DataMessageProto.PropertyMapOrBuilder> 
        getPmapOrBuilderList();
    sfs.proc.msg.DataMessageProto.PropertyMapOrBuilder getPmapOrBuilder(
        int index);
  }
  public static final class PropertyMessage extends
      com.google.protobuf.GeneratedMessage
      implements PropertyMessageOrBuilder {
    // Use PropertyMessage.newBuilder() to construct.
    private PropertyMessage(Builder builder) {
      super(builder);
    }
    private PropertyMessage(boolean noInit) {}
    
    private static final PropertyMessage defaultInstance;
    public static PropertyMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public PropertyMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sfs.proc.msg.DataMessageProto.internal_static_sfs_proc_msg_PropertyMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sfs.proc.msg.DataMessageProto.internal_static_sfs_proc_msg_PropertyMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string description = 1;
    public static final int DESCRIPTION_FIELD_NUMBER = 1;
    private java.lang.Object description_;
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          description_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .sfs.proc.msg.PropertyMap pmap = 2;
    public static final int PMAP_FIELD_NUMBER = 2;
    private java.util.List<sfs.proc.msg.DataMessageProto.PropertyMap> pmap_;
    public java.util.List<sfs.proc.msg.DataMessageProto.PropertyMap> getPmapList() {
      return pmap_;
    }
    public java.util.List<? extends sfs.proc.msg.DataMessageProto.PropertyMapOrBuilder> 
        getPmapOrBuilderList() {
      return pmap_;
    }
    public int getPmapCount() {
      return pmap_.size();
    }
    public sfs.proc.msg.DataMessageProto.PropertyMap getPmap(int index) {
      return pmap_.get(index);
    }
    public sfs.proc.msg.DataMessageProto.PropertyMapOrBuilder getPmapOrBuilder(
        int index) {
      return pmap_.get(index);
    }
    
    private void initFields() {
      description_ = "";
      pmap_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getPmapCount(); i++) {
        if (!getPmap(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDescriptionBytes());
      }
      for (int i = 0; i < pmap_.size(); i++) {
        output.writeMessage(2, pmap_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDescriptionBytes());
      }
      for (int i = 0; i < pmap_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, pmap_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static sfs.proc.msg.DataMessageProto.PropertyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sfs.proc.msg.DataMessageProto.PropertyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sfs.proc.msg.DataMessageProto.PropertyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sfs.proc.msg.DataMessageProto.PropertyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sfs.proc.msg.DataMessageProto.PropertyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sfs.proc.msg.DataMessageProto.PropertyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static sfs.proc.msg.DataMessageProto.PropertyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sfs.proc.msg.DataMessageProto.PropertyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sfs.proc.msg.DataMessageProto.PropertyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sfs.proc.msg.DataMessageProto.PropertyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(sfs.proc.msg.DataMessageProto.PropertyMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements sfs.proc.msg.DataMessageProto.PropertyMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sfs.proc.msg.DataMessageProto.internal_static_sfs_proc_msg_PropertyMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sfs.proc.msg.DataMessageProto.internal_static_sfs_proc_msg_PropertyMessage_fieldAccessorTable;
      }
      
      // Construct using sfs.proc.msg.DataMessageProto.PropertyMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPmapFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (pmapBuilder_ == null) {
          pmap_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          pmapBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sfs.proc.msg.DataMessageProto.PropertyMessage.getDescriptor();
      }
      
      public sfs.proc.msg.DataMessageProto.PropertyMessage getDefaultInstanceForType() {
        return sfs.proc.msg.DataMessageProto.PropertyMessage.getDefaultInstance();
      }
      
      public sfs.proc.msg.DataMessageProto.PropertyMessage build() {
        sfs.proc.msg.DataMessageProto.PropertyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private sfs.proc.msg.DataMessageProto.PropertyMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        sfs.proc.msg.DataMessageProto.PropertyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public sfs.proc.msg.DataMessageProto.PropertyMessage buildPartial() {
        sfs.proc.msg.DataMessageProto.PropertyMessage result = new sfs.proc.msg.DataMessageProto.PropertyMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.description_ = description_;
        if (pmapBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            pmap_ = java.util.Collections.unmodifiableList(pmap_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.pmap_ = pmap_;
        } else {
          result.pmap_ = pmapBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sfs.proc.msg.DataMessageProto.PropertyMessage) {
          return mergeFrom((sfs.proc.msg.DataMessageProto.PropertyMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(sfs.proc.msg.DataMessageProto.PropertyMessage other) {
        if (other == sfs.proc.msg.DataMessageProto.PropertyMessage.getDefaultInstance()) return this;
        if (other.hasDescription()) {
          setDescription(other.getDescription());
        }
        if (pmapBuilder_ == null) {
          if (!other.pmap_.isEmpty()) {
            if (pmap_.isEmpty()) {
              pmap_ = other.pmap_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePmapIsMutable();
              pmap_.addAll(other.pmap_);
            }
            onChanged();
          }
        } else {
          if (!other.pmap_.isEmpty()) {
            if (pmapBuilder_.isEmpty()) {
              pmapBuilder_.dispose();
              pmapBuilder_ = null;
              pmap_ = other.pmap_;
              bitField0_ = (bitField0_ & ~0x00000002);
              pmapBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPmapFieldBuilder() : null;
            } else {
              pmapBuilder_.addAllMessages(other.pmap_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getPmapCount(); i++) {
          if (!getPmap(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              description_ = input.readBytes();
              break;
            }
            case 18: {
              sfs.proc.msg.DataMessageProto.PropertyMap.Builder subBuilder = sfs.proc.msg.DataMessageProto.PropertyMap.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPmap(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string description = 1;
      private java.lang.Object description_ = "";
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDescription(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        description_ = value;
        onChanged();
        return this;
      }
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000001);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      void setDescription(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        description_ = value;
        onChanged();
      }
      
      // repeated .sfs.proc.msg.PropertyMap pmap = 2;
      private java.util.List<sfs.proc.msg.DataMessageProto.PropertyMap> pmap_ =
        java.util.Collections.emptyList();
      private void ensurePmapIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          pmap_ = new java.util.ArrayList<sfs.proc.msg.DataMessageProto.PropertyMap>(pmap_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          sfs.proc.msg.DataMessageProto.PropertyMap, sfs.proc.msg.DataMessageProto.PropertyMap.Builder, sfs.proc.msg.DataMessageProto.PropertyMapOrBuilder> pmapBuilder_;
      
      public java.util.List<sfs.proc.msg.DataMessageProto.PropertyMap> getPmapList() {
        if (pmapBuilder_ == null) {
          return java.util.Collections.unmodifiableList(pmap_);
        } else {
          return pmapBuilder_.getMessageList();
        }
      }
      public int getPmapCount() {
        if (pmapBuilder_ == null) {
          return pmap_.size();
        } else {
          return pmapBuilder_.getCount();
        }
      }
      public sfs.proc.msg.DataMessageProto.PropertyMap getPmap(int index) {
        if (pmapBuilder_ == null) {
          return pmap_.get(index);
        } else {
          return pmapBuilder_.getMessage(index);
        }
      }
      public Builder setPmap(
          int index, sfs.proc.msg.DataMessageProto.PropertyMap value) {
        if (pmapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePmapIsMutable();
          pmap_.set(index, value);
          onChanged();
        } else {
          pmapBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setPmap(
          int index, sfs.proc.msg.DataMessageProto.PropertyMap.Builder builderForValue) {
        if (pmapBuilder_ == null) {
          ensurePmapIsMutable();
          pmap_.set(index, builderForValue.build());
          onChanged();
        } else {
          pmapBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addPmap(sfs.proc.msg.DataMessageProto.PropertyMap value) {
        if (pmapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePmapIsMutable();
          pmap_.add(value);
          onChanged();
        } else {
          pmapBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addPmap(
          int index, sfs.proc.msg.DataMessageProto.PropertyMap value) {
        if (pmapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePmapIsMutable();
          pmap_.add(index, value);
          onChanged();
        } else {
          pmapBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addPmap(
          sfs.proc.msg.DataMessageProto.PropertyMap.Builder builderForValue) {
        if (pmapBuilder_ == null) {
          ensurePmapIsMutable();
          pmap_.add(builderForValue.build());
          onChanged();
        } else {
          pmapBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addPmap(
          int index, sfs.proc.msg.DataMessageProto.PropertyMap.Builder builderForValue) {
        if (pmapBuilder_ == null) {
          ensurePmapIsMutable();
          pmap_.add(index, builderForValue.build());
          onChanged();
        } else {
          pmapBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllPmap(
          java.lang.Iterable<? extends sfs.proc.msg.DataMessageProto.PropertyMap> values) {
        if (pmapBuilder_ == null) {
          ensurePmapIsMutable();
          super.addAll(values, pmap_);
          onChanged();
        } else {
          pmapBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearPmap() {
        if (pmapBuilder_ == null) {
          pmap_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          pmapBuilder_.clear();
        }
        return this;
      }
      public Builder removePmap(int index) {
        if (pmapBuilder_ == null) {
          ensurePmapIsMutable();
          pmap_.remove(index);
          onChanged();
        } else {
          pmapBuilder_.remove(index);
        }
        return this;
      }
      public sfs.proc.msg.DataMessageProto.PropertyMap.Builder getPmapBuilder(
          int index) {
        return getPmapFieldBuilder().getBuilder(index);
      }
      public sfs.proc.msg.DataMessageProto.PropertyMapOrBuilder getPmapOrBuilder(
          int index) {
        if (pmapBuilder_ == null) {
          return pmap_.get(index);  } else {
          return pmapBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends sfs.proc.msg.DataMessageProto.PropertyMapOrBuilder> 
           getPmapOrBuilderList() {
        if (pmapBuilder_ != null) {
          return pmapBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(pmap_);
        }
      }
      public sfs.proc.msg.DataMessageProto.PropertyMap.Builder addPmapBuilder() {
        return getPmapFieldBuilder().addBuilder(
            sfs.proc.msg.DataMessageProto.PropertyMap.getDefaultInstance());
      }
      public sfs.proc.msg.DataMessageProto.PropertyMap.Builder addPmapBuilder(
          int index) {
        return getPmapFieldBuilder().addBuilder(
            index, sfs.proc.msg.DataMessageProto.PropertyMap.getDefaultInstance());
      }
      public java.util.List<sfs.proc.msg.DataMessageProto.PropertyMap.Builder> 
           getPmapBuilderList() {
        return getPmapFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          sfs.proc.msg.DataMessageProto.PropertyMap, sfs.proc.msg.DataMessageProto.PropertyMap.Builder, sfs.proc.msg.DataMessageProto.PropertyMapOrBuilder> 
          getPmapFieldBuilder() {
        if (pmapBuilder_ == null) {
          pmapBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              sfs.proc.msg.DataMessageProto.PropertyMap, sfs.proc.msg.DataMessageProto.PropertyMap.Builder, sfs.proc.msg.DataMessageProto.PropertyMapOrBuilder>(
                  pmap_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          pmap_ = null;
        }
        return pmapBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:sfs.proc.msg.PropertyMessage)
    }
    
    static {
      defaultInstance = new PropertyMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:sfs.proc.msg.PropertyMessage)
  }
  
  public interface PropertyMapOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint32 idx = 1;
    boolean hasIdx();
    int getIdx();
    
    // required string label = 2;
    boolean hasLabel();
    String getLabel();
  }
  public static final class PropertyMap extends
      com.google.protobuf.GeneratedMessage
      implements PropertyMapOrBuilder {
    // Use PropertyMap.newBuilder() to construct.
    private PropertyMap(Builder builder) {
      super(builder);
    }
    private PropertyMap(boolean noInit) {}
    
    private static final PropertyMap defaultInstance;
    public static PropertyMap getDefaultInstance() {
      return defaultInstance;
    }
    
    public PropertyMap getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sfs.proc.msg.DataMessageProto.internal_static_sfs_proc_msg_PropertyMap_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sfs.proc.msg.DataMessageProto.internal_static_sfs_proc_msg_PropertyMap_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint32 idx = 1;
    public static final int IDX_FIELD_NUMBER = 1;
    private int idx_;
    public boolean hasIdx() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getIdx() {
      return idx_;
    }
    
    // required string label = 2;
    public static final int LABEL_FIELD_NUMBER = 2;
    private java.lang.Object label_;
    public boolean hasLabel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getLabel() {
      java.lang.Object ref = label_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          label_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      idx_ = 0;
      label_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasIdx()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLabel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, idx_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getLabelBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, idx_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getLabelBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static sfs.proc.msg.DataMessageProto.PropertyMap parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sfs.proc.msg.DataMessageProto.PropertyMap parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sfs.proc.msg.DataMessageProto.PropertyMap parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sfs.proc.msg.DataMessageProto.PropertyMap parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sfs.proc.msg.DataMessageProto.PropertyMap parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sfs.proc.msg.DataMessageProto.PropertyMap parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static sfs.proc.msg.DataMessageProto.PropertyMap parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sfs.proc.msg.DataMessageProto.PropertyMap parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sfs.proc.msg.DataMessageProto.PropertyMap parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sfs.proc.msg.DataMessageProto.PropertyMap parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(sfs.proc.msg.DataMessageProto.PropertyMap prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements sfs.proc.msg.DataMessageProto.PropertyMapOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sfs.proc.msg.DataMessageProto.internal_static_sfs_proc_msg_PropertyMap_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sfs.proc.msg.DataMessageProto.internal_static_sfs_proc_msg_PropertyMap_fieldAccessorTable;
      }
      
      // Construct using sfs.proc.msg.DataMessageProto.PropertyMap.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        idx_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        label_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sfs.proc.msg.DataMessageProto.PropertyMap.getDescriptor();
      }
      
      public sfs.proc.msg.DataMessageProto.PropertyMap getDefaultInstanceForType() {
        return sfs.proc.msg.DataMessageProto.PropertyMap.getDefaultInstance();
      }
      
      public sfs.proc.msg.DataMessageProto.PropertyMap build() {
        sfs.proc.msg.DataMessageProto.PropertyMap result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private sfs.proc.msg.DataMessageProto.PropertyMap buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        sfs.proc.msg.DataMessageProto.PropertyMap result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public sfs.proc.msg.DataMessageProto.PropertyMap buildPartial() {
        sfs.proc.msg.DataMessageProto.PropertyMap result = new sfs.proc.msg.DataMessageProto.PropertyMap(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.idx_ = idx_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.label_ = label_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sfs.proc.msg.DataMessageProto.PropertyMap) {
          return mergeFrom((sfs.proc.msg.DataMessageProto.PropertyMap)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(sfs.proc.msg.DataMessageProto.PropertyMap other) {
        if (other == sfs.proc.msg.DataMessageProto.PropertyMap.getDefaultInstance()) return this;
        if (other.hasIdx()) {
          setIdx(other.getIdx());
        }
        if (other.hasLabel()) {
          setLabel(other.getLabel());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasIdx()) {
          
          return false;
        }
        if (!hasLabel()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              idx_ = input.readUInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              label_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint32 idx = 1;
      private int idx_ ;
      public boolean hasIdx() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getIdx() {
        return idx_;
      }
      public Builder setIdx(int value) {
        bitField0_ |= 0x00000001;
        idx_ = value;
        onChanged();
        return this;
      }
      public Builder clearIdx() {
        bitField0_ = (bitField0_ & ~0x00000001);
        idx_ = 0;
        onChanged();
        return this;
      }
      
      // required string label = 2;
      private java.lang.Object label_ = "";
      public boolean hasLabel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getLabel() {
        java.lang.Object ref = label_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          label_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLabel(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        label_ = value;
        onChanged();
        return this;
      }
      public Builder clearLabel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        label_ = getDefaultInstance().getLabel();
        onChanged();
        return this;
      }
      void setLabel(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        label_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:sfs.proc.msg.PropertyMap)
    }
    
    static {
      defaultInstance = new PropertyMap(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:sfs.proc.msg.PropertyMap)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sfs_proc_msg_DataMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sfs_proc_msg_DataMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sfs_proc_msg_TimeValSet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sfs_proc_msg_TimeValSet_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sfs_proc_msg_PropertyMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sfs_proc_msg_PropertyMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sfs_proc_msg_PropertyMap_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sfs_proc_msg_PropertyMap_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021datamessage.proto\022\014sfs.proc.msg\"\340\001\n\013Da" +
      "taMessage\022\017\n\007srcpath\030\001 \001(\t\022&\n\004data\030\002 \003(\013" +
      "2\030.sfs.proc.msg.TimeValSet\0221\n\nproperties" +
      "\030\003 \001(\0132\035.sfs.proc.msg.PropertyMessage\0227\n" +
      "\004type\030\t \002(\0162).sfs.proc.msg.DataMessage.D" +
      "ataMessageType\",\n\017DataMessageType\022\013\n\007DAT" +
      "A_IN\020\001\022\014\n\010DATA_OUT\020\002\")\n\nTimeValSet\022\n\n\002ts" +
      "\030\001 \001(\004\022\017\n\003val\030\002 \003(\004B\002\020\001\"O\n\017PropertyMessa" +
      "ge\022\023\n\013description\030\001 \001(\t\022\'\n\004pmap\030\002 \003(\0132\031." +
      "sfs.proc.msg.PropertyMap\")\n\013PropertyMap\022",
      "\013\n\003idx\030\001 \002(\r\022\r\n\005label\030\002 \002(\tB\022B\020DataMessa" +
      "geProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_sfs_proc_msg_DataMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_sfs_proc_msg_DataMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sfs_proc_msg_DataMessage_descriptor,
              new java.lang.String[] { "Srcpath", "Data", "Properties", "Type", },
              sfs.proc.msg.DataMessageProto.DataMessage.class,
              sfs.proc.msg.DataMessageProto.DataMessage.Builder.class);
          internal_static_sfs_proc_msg_TimeValSet_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_sfs_proc_msg_TimeValSet_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sfs_proc_msg_TimeValSet_descriptor,
              new java.lang.String[] { "Ts", "Val", },
              sfs.proc.msg.DataMessageProto.TimeValSet.class,
              sfs.proc.msg.DataMessageProto.TimeValSet.Builder.class);
          internal_static_sfs_proc_msg_PropertyMessage_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_sfs_proc_msg_PropertyMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sfs_proc_msg_PropertyMessage_descriptor,
              new java.lang.String[] { "Description", "Pmap", },
              sfs.proc.msg.DataMessageProto.PropertyMessage.class,
              sfs.proc.msg.DataMessageProto.PropertyMessage.Builder.class);
          internal_static_sfs_proc_msg_PropertyMap_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_sfs_proc_msg_PropertyMap_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sfs_proc_msg_PropertyMap_descriptor,
              new java.lang.String[] { "Idx", "Label", },
              sfs.proc.msg.DataMessageProto.PropertyMap.class,
              sfs.proc.msg.DataMessageProto.PropertyMap.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
