// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consolemsg.proto

package sfs.proc.console.msg;

public final class ConsoleMessageProto {
  private ConsoleMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ConsoleMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .sfs.proc.console.msg.ConsoleMessage.ConsoleMessageType type = 1;
    boolean hasType();
    sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage.ConsoleMessageType getType();
    
    // optional string procPath = 2;
    boolean hasProcPath();
    String getProcPath();
    
    // optional string data = 3;
    boolean hasData();
    String getData();
  }
  public static final class ConsoleMessage extends
      com.google.protobuf.GeneratedMessage
      implements ConsoleMessageOrBuilder {
    // Use ConsoleMessage.newBuilder() to construct.
    private ConsoleMessage(Builder builder) {
      super(builder);
    }
    private ConsoleMessage(boolean noInit) {}
    
    private static final ConsoleMessage defaultInstance;
    public static ConsoleMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public ConsoleMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sfs.proc.console.msg.ConsoleMessageProto.internal_static_sfs_proc_console_msg_ConsoleMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sfs.proc.console.msg.ConsoleMessageProto.internal_static_sfs_proc_console_msg_ConsoleMessage_fieldAccessorTable;
    }
    
    public enum ConsoleMessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      RELOAD(0, 1),
      INFO(1, 2),
      QUIT(2, 3),
      ;
      
      public static final int RELOAD_VALUE = 1;
      public static final int INFO_VALUE = 2;
      public static final int QUIT_VALUE = 3;
      
      
      public final int getNumber() { return value; }
      
      public static ConsoleMessageType valueOf(int value) {
        switch (value) {
          case 1: return RELOAD;
          case 2: return INFO;
          case 3: return QUIT;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<ConsoleMessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ConsoleMessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ConsoleMessageType>() {
              public ConsoleMessageType findValueByNumber(int number) {
                return ConsoleMessageType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final ConsoleMessageType[] VALUES = {
        RELOAD, INFO, QUIT, 
      };
      
      public static ConsoleMessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private ConsoleMessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:sfs.proc.console.msg.ConsoleMessage.ConsoleMessageType)
    }
    
    private int bitField0_;
    // required .sfs.proc.console.msg.ConsoleMessage.ConsoleMessageType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage.ConsoleMessageType type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage.ConsoleMessageType getType() {
      return type_;
    }
    
    // optional string procPath = 2;
    public static final int PROCPATH_FIELD_NUMBER = 2;
    private java.lang.Object procPath_;
    public boolean hasProcPath() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getProcPath() {
      java.lang.Object ref = procPath_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          procPath_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getProcPathBytes() {
      java.lang.Object ref = procPath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        procPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string data = 3;
    public static final int DATA_FIELD_NUMBER = 3;
    private java.lang.Object data_;
    public boolean hasData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          data_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      type_ = sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage.ConsoleMessageType.RELOAD;
      procPath_ = "";
      data_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getProcPathBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDataBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getProcPathBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDataBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sfs.proc.console.msg.ConsoleMessageProto.internal_static_sfs_proc_console_msg_ConsoleMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sfs.proc.console.msg.ConsoleMessageProto.internal_static_sfs_proc_console_msg_ConsoleMessage_fieldAccessorTable;
      }
      
      // Construct using sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage.ConsoleMessageType.RELOAD;
        bitField0_ = (bitField0_ & ~0x00000001);
        procPath_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage.getDescriptor();
      }
      
      public sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage getDefaultInstanceForType() {
        return sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage.getDefaultInstance();
      }
      
      public sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage build() {
        sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage buildPartial() {
        sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage result = new sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.procPath_ = procPath_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage) {
          return mergeFrom((sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage other) {
        if (other == sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasProcPath()) {
          setProcPath(other.getProcPath());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage.ConsoleMessageType value = sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage.ConsoleMessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              procPath_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              data_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .sfs.proc.console.msg.ConsoleMessage.ConsoleMessageType type = 1;
      private sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage.ConsoleMessageType type_ = sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage.ConsoleMessageType.RELOAD;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage.ConsoleMessageType getType() {
        return type_;
      }
      public Builder setType(sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage.ConsoleMessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage.ConsoleMessageType.RELOAD;
        onChanged();
        return this;
      }
      
      // optional string procPath = 2;
      private java.lang.Object procPath_ = "";
      public boolean hasProcPath() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getProcPath() {
        java.lang.Object ref = procPath_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          procPath_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setProcPath(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        procPath_ = value;
        onChanged();
        return this;
      }
      public Builder clearProcPath() {
        bitField0_ = (bitField0_ & ~0x00000002);
        procPath_ = getDefaultInstance().getProcPath();
        onChanged();
        return this;
      }
      void setProcPath(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        procPath_ = value;
        onChanged();
      }
      
      // optional string data = 3;
      private java.lang.Object data_ = "";
      public boolean hasData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setData(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        data_ = value;
        onChanged();
        return this;
      }
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      void setData(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        data_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:sfs.proc.console.msg.ConsoleMessage)
    }
    
    static {
      defaultInstance = new ConsoleMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:sfs.proc.console.msg.ConsoleMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sfs_proc_console_msg_ConsoleMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sfs_proc_console_msg_ConsoleMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020consolemsg.proto\022\024sfs.proc.console.msg" +
      "\"\255\001\n\016ConsoleMessage\022E\n\004type\030\001 \002(\01627.sfs." +
      "proc.console.msg.ConsoleMessage.ConsoleM" +
      "essageType\022\020\n\010procPath\030\002 \001(\t\022\014\n\004data\030\003 \001" +
      "(\t\"4\n\022ConsoleMessageType\022\n\n\006RELOAD\020\001\022\010\n\004" +
      "INFO\020\002\022\010\n\004QUIT\020\003B\025B\023ConsoleMessageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_sfs_proc_console_msg_ConsoleMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_sfs_proc_console_msg_ConsoleMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sfs_proc_console_msg_ConsoleMessage_descriptor,
              new java.lang.String[] { "Type", "ProcPath", "Data", },
              sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage.class,
              sfs.proc.console.msg.ConsoleMessageProto.ConsoleMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
